//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filmograf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Filmograf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _01Koc {
            get {
                object obj = ResourceManager.GetObject("_01Koc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02Boga {
            get {
                object obj = ResourceManager.GetObject("_02Boga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _03Ikizler {
            get {
                object obj = ResourceManager.GetObject("_03Ikizler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _04Yengec {
            get {
                object obj = ResourceManager.GetObject("_04Yengec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _05Aslan {
            get {
                object obj = ResourceManager.GetObject("_05Aslan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _06Basak {
            get {
                object obj = ResourceManager.GetObject("_06Basak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _07Terazi {
            get {
                object obj = ResourceManager.GetObject("_07Terazi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _08Akrep {
            get {
                object obj = ResourceManager.GetObject("_08Akrep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _09Yay {
            get {
                object obj = ResourceManager.GetObject("_09Yay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _10Oglak {
            get {
                object obj = ResourceManager.GetObject("_10Oglak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _11Kova {
            get {
                object obj = ResourceManager.GetObject("_11Kova", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12Balik {
            get {
                object obj = ResourceManager.GetObject("_12Balik", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap action_delete1 {
            get {
                object obj = ResourceManager.GetObject("action_delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balloon_bar_green {
            get {
                object obj = ResourceManager.GetObject("balloon_bar_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Customize {
            get {
                object obj = ResourceManager.GetObject("Customize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abanyom dili (Bantu dil ailesi)
        ///Abazaca
        ///Abhazca
        ///Adamorobe isaret dili (Isaret dili)
        ///Acarca
        ///Adigece
        ///Afrikaans
        ///Ahtnaca
        ///Almanca
        ///Altayca
        ///Amharca
        ///Aragonca
        ///Arberesce
        ///Aramice
        ///Aranese
        ///Arapca
        ///Arnavutca
        ///Asturyasca
        ///Asagi Tananaca
        ///Auvergnat dili
        ///Avarca
        ///Aymara dili
        ///Ayni dili
        ///Aynu dili
        ///Azerbaycanca
        ///Baskca
        ///Bantu
        ///Bati Apacicesi
        ///Bengalce
        ///Bretonca
        ///Beyaz Rusca
        ///Bosnakca
        ///Bulgarca
        ///Burgonyaca
        ///Buryatca
        ///Champenois
        ///Çecence
        ///Çekce
        ///Çilkotince
        ///Çince
        ///Çingene Dili
        ///Çukcice
        ///Çupikce
        ///Çuvasca
        ///Dakelce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Diller {
            get {
                return ResourceManager.GetString("Diller", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dizibolumu {
            get {
                object obj = ResourceManager.GetObject("dizibolumu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap duzenle {
            get {
                object obj = ResourceManager.GetObject("duzenle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap eee {
            get {
                object obj = ResourceManager.GetObject("eee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap f_AnaPencereIkon {
            get {
                object obj = ResourceManager.GetObject("f_AnaPencereIkon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;{baslik}&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///.body {
        ///	background-color: #AAAAAA;	
        ///}
        ///.taban {
        ///	width: 610px;
        ///	margin-top: 0px;
        ///	margin-left: 10px;
        ///}
        ///.filmAfisi {
        ///	background-color: #CCCCCC;
        ///	float: left;
        ///	height: 300px;
        ///	width: 230px;
        ///	margin-left: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FilmHtmlMetni {
            get {
                return ResourceManager.GetString("FilmHtmlMetni", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap filmlerklasoru {
            get {
                object obj = ResourceManager.GetObject("filmlerklasoru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,FilmNoir,GameShow,History,Horror,Music,Musical,Mystery,News,RealityTV,Romance,SciFi,Sport,TalkShow,Thriller,War,Western.
        /// </summary>
        internal static string FilmTurleri {
            get {
                return ResourceManager.GetString("FilmTurleri", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Floppy {
            get {
                object obj = ResourceManager.GetObject("Floppy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hepsinisilsimgesi {
            get {
                object obj = ResourceManager.GetObject("hepsinisilsimgesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info1 {
            get {
                object obj = ResourceManager.GetObject("info1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kirmizicarpi {
            get {
                object obj = ResourceManager.GetObject("kirmizicarpi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kisi {
            get {
                object obj = ResourceManager.GetObject("Kisi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisiekle {
            get {
                object obj = ResourceManager.GetObject("kisiekle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;title&gt;{baslik}&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///.body {
        ///	background-color: #AAAAAA;	
        ///}
        ///.taban {
        ///	width: 610px;
        ///	margin-top: 0px;
        ///	margin-left: 10px;
        ///}
        ///.kisiAfisi {
        ///	background-color: #CCCCCC;
        ///	float: left;
        ///	height: 300px;
        ///	width: 230px;
        ///	margin-left: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KisiHtmlMetni {
            get {
                return ResourceManager.GetString("KisiHtmlMetni", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap kutuphanesimgesi {
            get {
                object obj = ResourceManager.GetObject("kutuphanesimgesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maviasagiacil {
            get {
                object obj = ResourceManager.GetObject("maviasagiacil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap maviyildiz {
            get {
                object obj = ResourceManager.GetObject("maviyildiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Movies {
            get {
                object obj = ResourceManager.GetObject("Movies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Network {
            get {
                object obj = ResourceManager.GetObject("Network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;satirSol&quot;&gt;{filmAdi}&lt;/div&gt;
        ///    &lt;div id=&quot;satirSag&quot;&gt;{karakterAdi}&lt;/div&gt;.
        /// </summary>
        internal static string OynadigiFilmMetni {
            get {
                return ResourceManager.GetString("OynadigiFilmMetni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;satirSol&quot;&gt;{oyuncuAdi}&lt;/div&gt;
        ///    &lt;div id=&quot;satirSag&quot;&gt;{karakterAdi}&lt;/div&gt;.
        /// </summary>
        internal static string OyuncuKadrosuMetni {
            get {
                return ResourceManager.GetString("OyuncuKadrosuMetni", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PieDiagram {
            get {
                object obj = ResourceManager.GetObject("PieDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sag {
            get {
                object obj = ResourceManager.GetObject("sag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sariyildiz {
            get {
                object obj = ResourceManager.GetObject("sariyildiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sil1 {
            get {
                object obj = ResourceManager.GetObject("sil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sol {
            get {
                object obj = ResourceManager.GetObject("sol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afganistan
        ///Almanya
        ///Amerikan Samoa
        ///Amerika Birlesik Devletleri
        ///Andorra
        ///Angola
        ///Anguilla, Ingiltere
        ///Antigua ve Barbuda
        ///Arjantin
        ///Arnavutluk
        ///Aruba, Hollanda
        ///Avustralya
        ///Avusturya
        ///Azerbaycan
        ///Bahama Adalari
        ///Bahreyn
        ///Banglades
        ///Barbados
        ///Belcika
        ///Belize
        ///Benin
        ///Bermuda, Ingiltere
        ///Beyaz Rusya
        ///Bhutan
        ///Birlesik Arap Emirlikleri
        ///Birmanya (Myanmar)
        ///Bolivya
        ///Bosna Hersek
        ///Botswana
        ///Brezilya
        ///Brunei
        ///Bulgaristan
        ///Burkina Faso
        ///Burundi
        ///Cape Verde
        ///Cayman Adalari, Ingiltere
        ///Cebelitarik, Ingiltere
        ///Cezayi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ulkeler {
            get {
                return ResourceManager.GetString("Ulkeler", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap varsayilanfilmafisi {
            get {
                object obj = ResourceManager.GetObject("varsayilanfilmafisi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap varsayilanfilmafisi1 {
            get {
                object obj = ResourceManager.GetObject("varsayilanfilmafisi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yenifilmsimgesi {
            get {
                object obj = ResourceManager.GetObject("yenifilmsimgesi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yenile {
            get {
                object obj = ResourceManager.GetObject("yenile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yesilarti {
            get {
                object obj = ResourceManager.GetObject("yesilarti", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
